// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: greeter_server/api/Greeter.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_greeter_server_api_Greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_server_api_Greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_greeter_server_api_Greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloReply) Reset() {
	*x = SayHelloReply{}
	mi := &file_greeter_server_api_Greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloReply) ProtoMessage() {}

func (x *SayHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_server_api_Greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloReply.ProtoReflect.Descriptor instead.
func (*SayHelloReply) Descriptor() ([]byte, []int) {
	return file_greeter_server_api_Greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_greeter_server_api_Greeter_proto protoreflect.FileDescriptor

const file_greeter_server_api_Greeter_proto_rawDesc = "" +
	"\n" +
	" greeter_server/api/Greeter.proto\x12\x03api\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rSayHelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2A\n" +
	"\aGreeter\x126\n" +
	"\bSayHello\x12\x14.api.SayHelloRequest\x1a\x12.api.SayHelloReply\"\x00BFZDgithub.com/robert-pkg/base4go/examples/helloworld/greeter_server/apib\x06proto3"

var (
	file_greeter_server_api_Greeter_proto_rawDescOnce sync.Once
	file_greeter_server_api_Greeter_proto_rawDescData []byte
)

func file_greeter_server_api_Greeter_proto_rawDescGZIP() []byte {
	file_greeter_server_api_Greeter_proto_rawDescOnce.Do(func() {
		file_greeter_server_api_Greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greeter_server_api_Greeter_proto_rawDesc), len(file_greeter_server_api_Greeter_proto_rawDesc)))
	})
	return file_greeter_server_api_Greeter_proto_rawDescData
}

var file_greeter_server_api_Greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_greeter_server_api_Greeter_proto_goTypes = []any{
	(*SayHelloRequest)(nil), // 0: api.SayHelloRequest
	(*SayHelloReply)(nil),   // 1: api.SayHelloReply
}
var file_greeter_server_api_Greeter_proto_depIdxs = []int32{
	0, // 0: api.Greeter.SayHello:input_type -> api.SayHelloRequest
	1, // 1: api.Greeter.SayHello:output_type -> api.SayHelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greeter_server_api_Greeter_proto_init() }
func file_greeter_server_api_Greeter_proto_init() {
	if File_greeter_server_api_Greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greeter_server_api_Greeter_proto_rawDesc), len(file_greeter_server_api_Greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_server_api_Greeter_proto_goTypes,
		DependencyIndexes: file_greeter_server_api_Greeter_proto_depIdxs,
		MessageInfos:      file_greeter_server_api_Greeter_proto_msgTypes,
	}.Build()
	File_greeter_server_api_Greeter_proto = out.File
	file_greeter_server_api_Greeter_proto_goTypes = nil
	file_greeter_server_api_Greeter_proto_depIdxs = nil
}
