// Code generated by respgen. DO NOT EDIT.
package api

func (r *SayHelloReply) SetCode(code int32) { r.Code = code }
func (r *SayHelloReply) SetMsg(msg string)  { r.Msg = msg }
func (r *SayHelloReply) SetData(data *SayHelloReplyData) { r.Data = data }

